#!/usr/bin/env python3
"""gigasnail-site builder — python3 stdlib only, no dependencies.

Turns content/<section>/<name>.md into <section>/<slug>.html using
templates/piece.html, and regenerates the entry list between the
ENTRIES:START / ENTRIES:END markers in each section's index.html.

Markdown supported: paragraphs, ## / ### headings, **bold**, *italic*,
`code`, [links](url), ![images](src), - lists, 1. lists, > quotes,
``` fenced code blocks, --- rules. A block starting with '<' passes
through as raw HTML (for <audio>, <div class="wip">, embeds, ...).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GENERATED_MARK = "<!-- generated by tools/build.py — edit the .md in content/, not this file -->"

SECTIONS = {
    "writing": {
        "label": "writing",
        "accent": "var(--slime)",
        "empty": "the archive is dispersed.<br><b>real, finished pieces only</b> — fragments are reassembling.",
    },
    "art": {
        "label": "art",
        "accent": "var(--mag)",
        "empty": "no sightings on record.<br><b>real pixels only</b> — the current form has not yet been photographed.",
    },
    "projects": {
        "label": "projects",
        "accent": "var(--cyan)",
        "empty": "nothing documented yet.<br><b>real projects only</b> — writeups are crawling out of the shell.",
    },
    "music": {
        "label": "music",
        "accent": "#ffb02e",
        "empty": "no transmissions yet.<br><b>real audio only</b> — the first signal is still being decoded.",
    },
}
NAV_ORDER = ["writing", "art", "projects", "music"]


def esc(t):
    return t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def inline(t):
    t = esc(t)
    t = re.sub(r"`([^`]+)`", r"<code>\1</code>", t)
    t = re.sub(r"!\[([^\]]*)\]\(([^)\s]+)\)", r'<img alt="\1" src="\2" loading="lazy">', t)
    t = re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)", r'<a href="\2">\1</a>', t)
    t = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", t)
    t = re.sub(r"\*([^*]+)\*", r"<em>\1</em>", t)
    return t


def md_to_html(md):
    out = []
    lines = md.split("\n")
    i = 0
    n = len(lines)
    while i < n:
        line = lines[i]
        stripped = line.strip()
        if not stripped:
            i += 1
            continue
        # fenced code block
        if stripped.startswith("```"):
            i += 1
            code = []
            while i < n and not lines[i].strip().startswith("```"):
                code.append(esc(lines[i]))
                i += 1
            i += 1  # closing fence
            out.append("<pre><code>" + "\n".join(code) + "</code></pre>")
            continue
        # raw HTML block: pass through until blank line
        if stripped.startswith("<"):
            block = []
            while i < n and lines[i].strip():
                block.append(lines[i])
                i += 1
            out.append("\n".join(block))
            continue
        # headings (# and ## both map to h2; ### to h3)
        m = re.match(r"^(#{1,3})\s+(.*)$", stripped)
        if m:
            tag = "h3" if len(m.group(1)) == 3 else "h2"
            out.append(f"<{tag}>{inline(m.group(2))}</{tag}>")
            i += 1
            continue
        # horizontal rule
        if re.match(r"^(-{3,}|\*{3,})$", stripped):
            out.append("<hr>")
            i += 1
            continue
        # blockquote
        if stripped.startswith(">"):
            quote = []
            while i < n and lines[i].strip().startswith(">"):
                quote.append(inline(lines[i].strip()[1:].strip()))
                i += 1
            out.append("<blockquote><p>" + "<br>".join(quote) + "</p></blockquote>")
            continue
        # unordered list
        if re.match(r"^[-*]\s+", stripped):
            items = []
            while i < n and re.match(r"^[-*]\s+", lines[i].strip()):
                items.append("<li>" + inline(re.sub(r"^[-*]\s+", "", lines[i].strip())) + "</li>")
                i += 1
            out.append("<ul>" + "".join(items) + "</ul>")
            continue
        # ordered list
        if re.match(r"^\d+\.\s+", stripped):
            items = []
            while i < n and re.match(r"^\d+\.\s+", lines[i].strip()):
                items.append("<li>" + inline(re.sub(r"^\d+\.\s+", "", lines[i].strip())) + "</li>")
                i += 1
            out.append("<ol>" + "".join(items) + "</ol>")
            continue
        # paragraph: accumulate until blank line
        para = []
        while i < n and lines[i].strip() and not re.match(r"^(#{1,3}\s|[-*]\s|\d+\.\s|>|```|<)", lines[i].strip()):
            para.append(lines[i].strip())
            i += 1
        out.append("<p>" + inline(" ".join(para)) + "</p>")
    return "\n\n".join(out)


def parse_frontmatter(text, path):
    if not text.startswith("---"):
        sys.exit(f"error: {path} has no frontmatter (must start with ---)")
    try:
        _, fm, body = text.split("---", 2)
    except ValueError:
        sys.exit(f"error: {path} frontmatter is not closed with ---")
    meta = {}
    for line in fm.strip().split("\n"):
        if ":" in line:
            k, v = line.split(":", 1)
            meta[k.strip()] = v.strip()
    return meta, body.strip()


def build():
    template = (ROOT / "templates" / "piece.html").read_text(encoding="utf-8")
    for section, cfg in SECTIONS.items():
        src_dir = ROOT / "content" / section
        out_dir = ROOT / section
        pieces = []

        for md_file in sorted(src_dir.glob("*.md")) if src_dir.is_dir() else []:
            meta, body = parse_frontmatter(md_file.read_text(encoding="utf-8"), md_file)
            slug = meta.get("slug") or re.sub(r"^\d{4}-\d{2}(-\d{2})?-", "", md_file.stem)
            title = meta.get("title") or slug.replace("-", " ")
            date = meta.get("date") or (re.match(r"^(\d{4}-\d{2})", md_file.stem) or [None, ""])[1]
            if not date:
                sys.exit(f"error: {md_file} needs a date: (or a YYYY-MM filename prefix)")
            summary = meta.get("summary", "")
            sub = meta.get("sub") or f"{date}."

            nav = []
            for s in NAV_ORDER:
                here = ' class="here"' if s == section else ""
                nav.append(f'      <a{here} href="../{s}/">{SECTIONS[s]["label"]}</a>')

            page = (
                template
                .replace("{{TITLE_UPPER}}", esc(title.upper()))
                .replace("{{TITLE}}", esc(title))
                .replace("{{ACCENT}}", cfg["accent"])
                .replace("{{SECTION_LABEL}}", cfg["label"])
                .replace("{{SUB}}", inline(sub))
                .replace("{{NAV}}", "\n".join(nav))
                .replace("{{CONTENT}}", md_to_html(body))
                .replace("</head>", GENERATED_MARK + "\n</head>")
            )
            (out_dir / f"{slug}.html").write_text(page, encoding="utf-8")
            pieces.append({
                "slug": slug, "title": title, "date": date, "summary": summary,
                "order": int(meta.get("order", 999)),
            })
            print(f"  built {section}/{slug}.html")

        # remove generated pages whose source .md is gone
        keep = {p["slug"] for p in pieces}
        for html_file in out_dir.glob("*.html"):
            if html_file.name == "index.html" or html_file.stem in keep:
                continue
            if GENERATED_MARK in html_file.read_text(encoding="utf-8"):
                html_file.unlink()
                print(f"  removed stale {section}/{html_file.name}")

        # regenerate index entry list between markers
        pieces.sort(key=lambda p: (p["date"], -p["order"], p["slug"]), reverse=True)
        if pieces:
            blocks = []
            for p in pieces:
                blocks.append(
                    '  <article class="entry">\n'
                    f'    <div class="meta">{esc(p["date"])}</div>\n'
                    f'    <h3><a href="{p["slug"]}.html">{esc(p["title"])}</a></h3>\n'
                    f'    <p>{inline(p["summary"])}</p>\n'
                    "  </article>"
                )
            entries = "\n\n".join(blocks)
        else:
            entries = f'  <div class="empty">{cfg["empty"]}</div>'

        index_file = out_dir / "index.html"
        index = index_file.read_text(encoding="utf-8")
        new_index, count = re.subn(
            r"(<!-- ENTRIES:START[^>]*-->).*?(<!-- ENTRIES:END -->)",
            lambda m: m.group(1) + "\n" + entries + "\n  " + m.group(2),
            index, flags=re.S,
        )
        if count != 1:
            sys.exit(f"error: ENTRIES markers not found in {index_file}")
        if new_index != index:
            index_file.write_text(new_index, encoding="utf-8")
            print(f"  updated {section}/index.html")


if __name__ == "__main__":
    build()
    print("🐌 build done.")
